name: Oracle Auto Instance Creation

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run creation script
        env:
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
        run: |
          mkdir -p ~/.oci
          echo "$OCI_KEY_FILE" > ~/.oci/oci_api_key.pem
          python main.py
